# Generated by Django 5.1.7 on 2025-05-04 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('ano', models.IntegerField()),
                ('acessorios', models.ManyToManyField(blank=True, related_name='veiculos', to='core.acessorio')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='core.cor')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='core.modelo')),
            ],
        ),
    ]
